extends: default

ignore:
  - .github/
  - .yamllint.yml

rules:
  line-length: disable
  truthy:
    allowed-values: ['true', 'false']
  comments:
    min-spaces-from-content: 1
  indentation:
    spaces: 2
    indent-sequences: consistent
