apiVersion: v1
kind: Pod
metadata:
  name: linkding-migrator
  namespace: linkding
spec:
  restartPolicy: Never
  securityContext:
    runAsUser: 0
  containers:
    - name: migrator
      image: alpine:3.20
      command: ["/bin/sh", "-c", "sleep 36000"]
      volumeMounts:
        - name: old-data
          mountPath: /old-data
        - name: new-data
          mountPath: /new-data
  volumes:
    - name: old-data
      hostPath:
        path: /srv/linkding/data
        type: DirectoryOrCreate
    - name: new-data
      persistentVolumeClaim:
        claimName: data
