apiVersion: v1
kind: Secret
metadata:
    name: linkding-secret
    namespace: linkding
stringData:
    ld_superuser_password: ENC[AES256_GCM,data:mZDAaelVTqBIvtpWhsWVnfL6Z7Kh,iv:fL7EEogoHaxwjjP7JbQz0mlPpGoiXXREvAXRj5ZVw/g=,tag:K7mW1r1k4dH+J2mGNLznTA==,type:str]
sops:
    age:
        - recipient: age1m5kknfc3qvyut6cwjmg45d542hl3h2p6v0zrsnwenc970xvcudxsp4dw08
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSXl0UDl6YWR3bERvcDhC
            RDZzb2VNR29GaVVxaExBMWhWNWJDUUtWb2pnCnJjdS9CbzkvdWZDTE4zM2VGRU5a
            QWZGL3hGQzVlUWRtOXZ6a1l6NGRMRXMKLS0tIHpNVWoxVFNSSS9QS28yYnZGcWU2
            TlRlazJzUytyMjcvdXV0ZWI0ZVA3RDQKL5ubZKGmaYE5f8q02Mhc7UpVItrFAaG1
            aUbjG/2fzdxhJuruDxJPKZSYSfPB2DC6PURnzHBBNnJycg5laM9F9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T09:22:18Z"
    mac: ENC[AES256_GCM,data:xtKvUNPLIAFsW3B9Hj0nrjgCM9nDyGb9Kh1Hc8GA5iBN7j3pgZsG8jixn8I73RZvPcmPxf7COStaYB9yUmVP4oZeWnUcY7I8l9oECJHQ1O3U0hk346xz/3iU9vBwwSOc178ss93cowFxSL9ZP7wp56oiFOzTJRGaK1yhYZfVeHM=,iv:DmsOSti4DawYSj8nHdpuXFfcxdqQIfjBEKC/8pp2JaA=,tag:TB+9GEyeHMOXKfUG0iAWXw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
