apiVersion: v1
kind: Secret
metadata:
  name: linkding-secret
  namespace: linkding
stringData:
  ld_superuser_password: ENC[AES256_GCM,data:mZDAaelVTqBIvtpWhsWVnfL6Z7Kh,iv:fL7EEogoHaxwjjP7JbQz0mlPpGoiXXREvAXRj5ZVw/g=,tag:K7mW1r1k4dH+J2mGNLznTA==,type:str]
sops:
  age:
    - recipient: age1m5kknfc3qvyut6cwjmg45d542hl3h2p6v0zrsnwenc970xvcudxsp4dw08
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSXl0UDl6YWR3bERvcDhC
        RDZzb2VNR29GaVVxaExBMWhWNWJDUUtWb2pnCnJjdS9CbzkvdWZDTE4zM2VGRU5a
        QWZGL3hGQzVlUWRtOXZ6a1l6NGRMRXMKLS0tIHpNVWoxVFNSSS9QS28yYnZGcWU2
        TlRlazJzUytyMjcvdXV0ZWI0ZVA3RDQKL5ubZKGmaYE5f8q02Mhc7UpVItrFAaG1
        aUbjG/2fzdxhJuruDxJPKZSYSfPB2DC6PURnzHBBNnJycg5laM9F9Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-23T10:01:30Z"
  mac: ENC[AES256_GCM,data:Z0NWl6anm5gv2iN/aWa6JCWDQPMsUvhPVHFVoamBMIDhhRBG9Fb+n24GDx5X0KetRAQg9ZeJQuxMWgT2lCvo3SWRc81zW0vdTmmfSnK57H3a8uSghligfgvWFX2zhC2gSefnO1DceRw/ONdV25XW5y9UlYUurEaWdOJHPWhDR2U=,iv:Q2lWMY5KTJRQEk7uC/CQCVCiG56AtQcMu2JTypK16AM=,tag:YML84up2L890acGmZSK5hg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
