apiVersion: v1
kind: Secret
metadata:
    name: umami-secret
    namespace: umami
type: Opaque
stringData:
    app-secret: ENC[AES256_GCM,data:wx3VdiK5hXgIQgrEpw1YIBH2nYU+ecg=,iv:27dpc+bLIrmrWdL+dCYlTlVmbFZ/g9tZUnOCufH0FSc=,tag:9yvaw5OLgCTSzFK4eyfV/A==,type:str]
    database-url: ENC[AES256_GCM,data:1qKWe4/3ows6pTospajS/kawNMT+zxLIQOloaO4jeuAeBQseuFBslAoZio1sPJtiGYs2Av8Oa1AzpPM58mKF,iv:sRymQbsg/d4wlg/KLildyLYFWEBBEs1dIyFOAluVD1Y=,tag:DK7dl8Zt1Ap+mAOrOKch4g==,type:str]
sops:
    age:
        - recipient: age1m5kknfc3qvyut6cwjmg45d542hl3h2p6v0zrsnwenc970xvcudxsp4dw08
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYQUZRckFxb3dKY0N4N1ds
            VlZPdWZ4VEZYUmljaVJNcWhGOC9paE00TWc0CmZPQUhEb2x5c1dRZG16ZEIrN2Jy
            ejh5VWJkSXpESzVRK0FQbVlFTjhVVUEKLS0tIEZVbXAzbk5jWFZockpTd0lZSitn
            WDUwZ2dBMGhzQlc5RWgzMEl0di9BQ00Kv9xk2HRSE61z+DVMJbYj7sKBET2sGKvH
            i4DuXgFeA8r7BcEs8VOv6i+Ta0OozjvVyQdHSDGWfZBMHy13VZuAzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T09:35:14Z"
    mac: ENC[AES256_GCM,data:LNV2BPIZM4UvXy7FKhgm7mRqILQF3bsBSg7kbGFeIlPGHYn1dl21Cch5NASIE1QSbQ6+BddoefNT2gXrESEeECKPV/eTpimBxLS+uXDakA8CiGfsFUDeL74Me98AV1yVaEbCu12Iw2uG3uENmtJXYI4FFownREr+AENx+MNOwdo=,iv:CCZqmyUUbIASBeagIriFeZ9oh6CX2RM1Wzcqj92Kmnc=,tag:UdRrw+DX4JPGHqR1gLCvAQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
